CREATE TABLE public.couple_rituals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, title text NOT NULL, detail text, cadence text NOT NULL DEFAULT 'daily' CHECK (cadence IN ('daily','weekly')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.couple_rituals TO authenticated;
GRANT ALL ON public.couple_rituals TO service_role;
ALTER TABLE public.couple_rituals ENABLE ROW LEVEL SECURITY;
CREATE POLICY rituals_read ON public.couple_rituals FOR SELECT TO authenticated USING (auth.uid()=user_id OR public.same_space(user_id));
CREATE POLICY rituals_insert ON public.couple_rituals FOR INSERT TO authenticated WITH CHECK (auth.uid()=user_id);
CREATE POLICY rituals_update ON public.couple_rituals FOR UPDATE TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
CREATE POLICY rituals_delete ON public.couple_rituals FOR DELETE TO authenticated USING (auth.uid()=user_id);
CREATE TABLE public.ritual_completions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ritual_id uuid NOT NULL REFERENCES public.couple_rituals(id) ON DELETE CASCADE, user_id uuid NOT NULL, period date NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(ritual_id,user_id,period));
GRANT SELECT, INSERT, DELETE ON public.ritual_completions TO authenticated;
GRANT ALL ON public.ritual_completions TO service_role;
ALTER TABLE public.ritual_completions ENABLE ROW LEVEL SECURITY;
CREATE POLICY ritual_checks_read ON public.ritual_completions FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.couple_rituals r WHERE r.id=ritual_id AND (r.user_id=auth.uid() OR public.same_space(r.user_id))));
CREATE POLICY ritual_checks_insert ON public.ritual_completions FOR INSERT TO authenticated WITH CHECK (user_id=auth.uid() AND EXISTS(SELECT 1 FROM public.couple_rituals r WHERE r.id=ritual_id AND (r.user_id=auth.uid() OR public.same_space(r.user_id))));
CREATE POLICY ritual_checks_delete ON public.ritual_completions FOR DELETE TO authenticated USING (user_id=auth.uid());
CREATE TABLE public.care_cards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, title text NOT NULL, detail text NOT NULL, category text NOT NULL DEFAULT 'support' CHECK(category IN ('support','boundaries','joy')), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.care_cards TO authenticated;
GRANT ALL ON public.care_cards TO service_role;
ALTER TABLE public.care_cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY care_read ON public.care_cards FOR SELECT TO authenticated USING (auth.uid()=user_id OR public.same_space(user_id));
CREATE POLICY care_insert ON public.care_cards FOR INSERT TO authenticated WITH CHECK (auth.uid()=user_id);
CREATE POLICY care_update ON public.care_cards FOR UPDATE TO authenticated USING (auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);
CREATE POLICY care_delete ON public.care_cards FOR DELETE TO authenticated USING (auth.uid()=user_id);
ALTER PUBLICATION supabase_realtime ADD TABLE public.couple_rituals, public.ritual_completions, public.care_cards;
COMMENT ON TABLE public.couple_games IS 'DEPRECATED: Games section removed at user request; private history retained.';
COMMENT ON TABLE public.naval_fleets IS 'DEPRECATED: Games section removed; private history retained.';