/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCancionesRouteImport } from './routes/_authenticated/canciones'
import { Route as AuthenticatedCapsulasRouteImport } from './routes/_authenticated/capsulas'
import { Route as AuthenticatedCercaRouteImport } from './routes/_authenticated/cerca'
import { Route as AuthenticatedConexionRouteImport } from './routes/_authenticated/conexion'
import { Route as AuthenticatedCuponesRouteImport } from './routes/_authenticated/cupones'
import { Route as AuthenticatedDedicatoriasRouteImport } from './routes/_authenticated/dedicatorias'
import { Route as AuthenticatedDeseosRouteImport } from './routes/_authenticated/deseos'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedDiversionRouteImport } from './routes/_authenticated/diversion'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedLibroRouteImport } from './routes/_authenticated/libro'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedRetosRouteImport } from './routes/_authenticated/retos'
import { Route as AuthenticatedRuletaRouteImport } from './routes/_authenticated/ruleta'
import { Route as AuthenticatedTareasRouteImport } from './routes/_authenticated/tareas'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedConsejeroIndexRouteImport } from './routes/_authenticated/consejero.index'
import { Route as AuthenticatedConsejeroIdRouteImport } from './routes/_authenticated/consejero.$id'
import { Route as AuthenticatedNotasIndexRouteImport } from './routes/_authenticated/notas.index'
import { Route as AuthenticatedNotasIdRouteImport } from './routes/_authenticated/notas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCancionesRoute = AuthenticatedCancionesRouteImport.update({
  id: '/canciones',
  path: '/canciones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapsulasRoute = AuthenticatedCapsulasRouteImport.update({
  id: '/capsulas',
  path: '/capsulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCercaRoute = AuthenticatedCercaRouteImport.update({
  id: '/cerca',
  path: '/cerca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConexionRoute = AuthenticatedConexionRouteImport.update({
  id: '/conexion',
  path: '/conexion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuponesRoute = AuthenticatedCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDedicatoriasRoute =
  AuthenticatedDedicatoriasRouteImport.update({
    id: '/dedicatorias',
    path: '/dedicatorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeseosRoute = AuthenticatedDeseosRouteImport.update({
  id: '/deseos',
  path: '/deseos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiversionRoute = AuthenticatedDiversionRouteImport.update({
  id: '/diversion',
  path: '/diversion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibroRoute = AuthenticatedLibroRouteImport.update({
  id: '/libro',
  path: '/libro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetosRoute = AuthenticatedRetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRuletaRoute = AuthenticatedRuletaRouteImport.update({
  id: '/ruleta',
  path: '/ruleta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTareasRoute = AuthenticatedTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsejeroIndexRoute =
  AuthenticatedConsejeroIndexRouteImport.update({
    id: '/consejero/',
    path: '/consejero/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsejeroIdRoute =
  AuthenticatedConsejeroIdRouteImport.update({
    id: '/consejero/$id',
    path: '/consejero/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotasIndexRoute = AuthenticatedNotasIndexRouteImport.update({
  id: '/notas/',
  path: '/notas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasIdRoute = AuthenticatedNotasIdRouteImport.update({
  id: '/notas/$id',
  path: '/notas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citas': typeof CitasRoute
  '/fotos': typeof FotosRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/canciones': typeof AuthenticatedCancionesRoute
  '/capsulas': typeof AuthenticatedCapsulasRoute
  '/cerca': typeof AuthenticatedCercaRoute
  '/conexion': typeof AuthenticatedConexionRoute
  '/cupones': typeof AuthenticatedCuponesRoute
  '/dedicatorias': typeof AuthenticatedDedicatoriasRoute
  '/deseos': typeof AuthenticatedDeseosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/diversion': typeof AuthenticatedDiversionRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/libro': typeof AuthenticatedLibroRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/retos': typeof AuthenticatedRetosRoute
  '/ruleta': typeof AuthenticatedRuletaRoute
  '/tareas': typeof AuthenticatedTareasRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/api/chat': typeof ApiChatRoute
  '/consejero/$id': typeof AuthenticatedConsejeroIdRoute
  '/notas/$id': typeof AuthenticatedNotasIdRoute
  '/consejero/': typeof AuthenticatedConsejeroIndexRoute
  '/notas/': typeof AuthenticatedNotasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citas': typeof CitasRoute
  '/fotos': typeof FotosRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/canciones': typeof AuthenticatedCancionesRoute
  '/capsulas': typeof AuthenticatedCapsulasRoute
  '/cerca': typeof AuthenticatedCercaRoute
  '/conexion': typeof AuthenticatedConexionRoute
  '/cupones': typeof AuthenticatedCuponesRoute
  '/dedicatorias': typeof AuthenticatedDedicatoriasRoute
  '/deseos': typeof AuthenticatedDeseosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/diversion': typeof AuthenticatedDiversionRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/libro': typeof AuthenticatedLibroRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/retos': typeof AuthenticatedRetosRoute
  '/ruleta': typeof AuthenticatedRuletaRoute
  '/tareas': typeof AuthenticatedTareasRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/api/chat': typeof ApiChatRoute
  '/consejero/$id': typeof AuthenticatedConsejeroIdRoute
  '/notas/$id': typeof AuthenticatedNotasIdRoute
  '/consejero': typeof AuthenticatedConsejeroIndexRoute
  '/notas': typeof AuthenticatedNotasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/citas': typeof CitasRoute
  '/fotos': typeof FotosRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/canciones': typeof AuthenticatedCancionesRoute
  '/_authenticated/capsulas': typeof AuthenticatedCapsulasRoute
  '/_authenticated/cerca': typeof AuthenticatedCercaRoute
  '/_authenticated/conexion': typeof AuthenticatedConexionRoute
  '/_authenticated/cupones': typeof AuthenticatedCuponesRoute
  '/_authenticated/dedicatorias': typeof AuthenticatedDedicatoriasRoute
  '/_authenticated/deseos': typeof AuthenticatedDeseosRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/diversion': typeof AuthenticatedDiversionRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/libro': typeof AuthenticatedLibroRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/retos': typeof AuthenticatedRetosRoute
  '/_authenticated/ruleta': typeof AuthenticatedRuletaRoute
  '/_authenticated/tareas': typeof AuthenticatedTareasRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/consejero/$id': typeof AuthenticatedConsejeroIdRoute
  '/_authenticated/notas/$id': typeof AuthenticatedNotasIdRoute
  '/_authenticated/consejero/': typeof AuthenticatedConsejeroIndexRoute
  '/_authenticated/notas/': typeof AuthenticatedNotasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/citas'
    | '/fotos'
    | '/ajustes'
    | '/calendario'
    | '/canciones'
    | '/capsulas'
    | '/cerca'
    | '/conexion'
    | '/cupones'
    | '/dedicatorias'
    | '/deseos'
    | '/diario'
    | '/diversion'
    | '/galeria'
    | '/libro'
    | '/metas'
    | '/panel'
    | '/retos'
    | '/ruleta'
    | '/tareas'
    | '/videos'
    | '/api/chat'
    | '/consejero/$id'
    | '/notas/$id'
    | '/consejero/'
    | '/notas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/citas'
    | '/fotos'
    | '/ajustes'
    | '/calendario'
    | '/canciones'
    | '/capsulas'
    | '/cerca'
    | '/conexion'
    | '/cupones'
    | '/dedicatorias'
    | '/deseos'
    | '/diario'
    | '/diversion'
    | '/galeria'
    | '/libro'
    | '/metas'
    | '/panel'
    | '/retos'
    | '/ruleta'
    | '/tareas'
    | '/videos'
    | '/api/chat'
    | '/consejero/$id'
    | '/notas/$id'
    | '/consejero'
    | '/notas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/citas'
    | '/fotos'
    | '/_authenticated/ajustes'
    | '/_authenticated/calendario'
    | '/_authenticated/canciones'
    | '/_authenticated/capsulas'
    | '/_authenticated/cerca'
    | '/_authenticated/conexion'
    | '/_authenticated/cupones'
    | '/_authenticated/dedicatorias'
    | '/_authenticated/deseos'
    | '/_authenticated/diario'
    | '/_authenticated/diversion'
    | '/_authenticated/galeria'
    | '/_authenticated/libro'
    | '/_authenticated/metas'
    | '/_authenticated/panel'
    | '/_authenticated/retos'
    | '/_authenticated/ruleta'
    | '/_authenticated/tareas'
    | '/_authenticated/videos'
    | '/api/chat'
    | '/_authenticated/consejero/$id'
    | '/_authenticated/notas/$id'
    | '/_authenticated/consejero/'
    | '/_authenticated/notas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CitasRoute: typeof CitasRoute
  FotosRoute: typeof FotosRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canciones': {
      id: '/_authenticated/canciones'
      path: '/canciones'
      fullPath: '/canciones'
      preLoaderRoute: typeof AuthenticatedCancionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capsulas': {
      id: '/_authenticated/capsulas'
      path: '/capsulas'
      fullPath: '/capsulas'
      preLoaderRoute: typeof AuthenticatedCapsulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cerca': {
      id: '/_authenticated/cerca'
      path: '/cerca'
      fullPath: '/cerca'
      preLoaderRoute: typeof AuthenticatedCercaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conexion': {
      id: '/_authenticated/conexion'
      path: '/conexion'
      fullPath: '/conexion'
      preLoaderRoute: typeof AuthenticatedConexionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cupones': {
      id: '/_authenticated/cupones'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof AuthenticatedCuponesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dedicatorias': {
      id: '/_authenticated/dedicatorias'
      path: '/dedicatorias'
      fullPath: '/dedicatorias'
      preLoaderRoute: typeof AuthenticatedDedicatoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deseos': {
      id: '/_authenticated/deseos'
      path: '/deseos'
      fullPath: '/deseos'
      preLoaderRoute: typeof AuthenticatedDeseosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diversion': {
      id: '/_authenticated/diversion'
      path: '/diversion'
      fullPath: '/diversion'
      preLoaderRoute: typeof AuthenticatedDiversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/libro': {
      id: '/_authenticated/libro'
      path: '/libro'
      fullPath: '/libro'
      preLoaderRoute: typeof AuthenticatedLibroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retos': {
      id: '/_authenticated/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof AuthenticatedRetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ruleta': {
      id: '/_authenticated/ruleta'
      path: '/ruleta'
      fullPath: '/ruleta'
      preLoaderRoute: typeof AuthenticatedRuletaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tareas': {
      id: '/_authenticated/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AuthenticatedTareasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consejero/': {
      id: '/_authenticated/consejero/'
      path: '/consejero'
      fullPath: '/consejero/'
      preLoaderRoute: typeof AuthenticatedConsejeroIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consejero/$id': {
      id: '/_authenticated/consejero/$id'
      path: '/consejero/$id'
      fullPath: '/consejero/$id'
      preLoaderRoute: typeof AuthenticatedConsejeroIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas/': {
      id: '/_authenticated/notas/'
      path: '/notas'
      fullPath: '/notas/'
      preLoaderRoute: typeof AuthenticatedNotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas/$id': {
      id: '/_authenticated/notas/$id'
      path: '/notas/$id'
      fullPath: '/notas/$id'
      preLoaderRoute: typeof AuthenticatedNotasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCancionesRoute: typeof AuthenticatedCancionesRoute
  AuthenticatedCapsulasRoute: typeof AuthenticatedCapsulasRoute
  AuthenticatedCercaRoute: typeof AuthenticatedCercaRoute
  AuthenticatedConexionRoute: typeof AuthenticatedConexionRoute
  AuthenticatedCuponesRoute: typeof AuthenticatedCuponesRoute
  AuthenticatedDedicatoriasRoute: typeof AuthenticatedDedicatoriasRoute
  AuthenticatedDeseosRoute: typeof AuthenticatedDeseosRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedDiversionRoute: typeof AuthenticatedDiversionRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedLibroRoute: typeof AuthenticatedLibroRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedRetosRoute: typeof AuthenticatedRetosRoute
  AuthenticatedRuletaRoute: typeof AuthenticatedRuletaRoute
  AuthenticatedTareasRoute: typeof AuthenticatedTareasRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedConsejeroIdRoute: typeof AuthenticatedConsejeroIdRoute
  AuthenticatedNotasIdRoute: typeof AuthenticatedNotasIdRoute
  AuthenticatedConsejeroIndexRoute: typeof AuthenticatedConsejeroIndexRoute
  AuthenticatedNotasIndexRoute: typeof AuthenticatedNotasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCancionesRoute: AuthenticatedCancionesRoute,
  AuthenticatedCapsulasRoute: AuthenticatedCapsulasRoute,
  AuthenticatedCercaRoute: AuthenticatedCercaRoute,
  AuthenticatedConexionRoute: AuthenticatedConexionRoute,
  AuthenticatedCuponesRoute: AuthenticatedCuponesRoute,
  AuthenticatedDedicatoriasRoute: AuthenticatedDedicatoriasRoute,
  AuthenticatedDeseosRoute: AuthenticatedDeseosRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedDiversionRoute: AuthenticatedDiversionRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedLibroRoute: AuthenticatedLibroRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedRetosRoute: AuthenticatedRetosRoute,
  AuthenticatedRuletaRoute: AuthenticatedRuletaRoute,
  AuthenticatedTareasRoute: AuthenticatedTareasRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedConsejeroIdRoute: AuthenticatedConsejeroIdRoute,
  AuthenticatedNotasIdRoute: AuthenticatedNotasIdRoute,
  AuthenticatedConsejeroIndexRoute: AuthenticatedConsejeroIndexRoute,
  AuthenticatedNotasIndexRoute: AuthenticatedNotasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CitasRoute: CitasRoute,
  FotosRoute: FotosRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
